function deepFreeze(obj) {
    if (obj === null || typeof obj !== 'object') {
        return obj;
    }

    Object.getOwnPropertyNames(obj).forEach(function (prop) {
        const propValue = obj[prop];
        if (typeof propValue === 'object' && propValue !== null) {
            deepFreeze(propValue);
        }
    });

    return Object.freeze(obj);
}

const PUBLICATION_TEXTS = {
    methoden: {
        de: {
            title: "Methoden",
            introduction_title: "Einleitung",
            introduction_content: "Die korrekte prätherapeutische Einschätzung des Nodalstatus bei Patienten mit Rektumkarzinom ist entscheidend für die Wahl der optimalen Therapiestrategie und hat maßgeblichen Einfluss auf die Prognose. Während die Magnetresonanztomographie (MRT) als Standardverfahren für das lokale Staging gilt, bleibt die zuverlässige Differenzierung zwischen benignen und malignen mesorektalen Lymphknoten eine Herausforderung. Konventionelle morphologische Kriterien, die auf T2-gewichteten (T2w) Sequenzen basieren, weisen oft eine limitierte diagnostische Genauigkeit auf. Das Avocado Sign (AS), ein neuartiges kontrastmittelbasiertes MRT-Zeichen, das auf dem spezifischen Anreicherungsmuster von Lymphknoten in T1-gewichteten (T1w) Sequenzen beruht, zeigte in einer initialen monozentrischen Studie eine vielversprechende diagnostische Leistung für die Prädiktion des N-Status (Lurz M & Schäfer AO, Eur Radiol 2025; DOI: 10.1007/s00330-025-11462-y). Ziel der vorliegenden Studie war es, die diagnostische Güte des Avocado Signs im direkten Vergleich mit etablierten T2w-morphologischen Kriteriensets aus der Literatur sowie mit datengetriebenen, mittels Brute-Force-Analyse optimierten T2w-Kriterien auf demselben, gut charakterisierten Patientenkollektiv zu evaluieren.",
            studyPopulation_title: "Studienpopulation und Datenerhebung",
            studyPopulation_content: "Diese retrospektive Analyse basiert auf dem identischen, prospektiv evaluierten Patientenkollektiv der initialen Avocado-Sign-Studie (Lurz M & Schäfer AO, Eur Radiol 2025). In die Analyse wurden {{PATIENT_COUNT_GESAMT}} konsekutive Patienten mit histologisch gesichertem Adenokarzinom des Rektums eingeschlossen, die zwischen Januar 2020 und November 2023 eine standardisierte prätherapeutische MRT-Untersuchung des Beckens am Klinikum St. Georg, Leipzig, Deutschland, erhielten. Von diesen Patienten wurden {{PATIENT_COUNT_DIREKT_OP}} einer primären Operation ohne neoadjuvante Vorbehandlung unterzogen (Direkt-OP-Gruppe), während {{PATIENT_COUNT_NRCT}} Patienten eine neoadjuvante Radiochemotherapie (nRCT-Gruppe) mit anschließender chirurgischer Resektion erhielten. Die retrospektive Auswertung der pseudonymisierten Patientendaten und Bilddaten für diese Folgestudie erfolgte konform mit dem positiven Votum der zuständigen Ethikkommission des Klinikums St. Georg Leipzig (Ethik-Votum: {{ETHIK_VOTUM_NUMMER}}); alle Patienten hatten zuvor ihr schriftliches Einverständnis zur wissenschaftlichen Nutzung ihrer Daten im Rahmen der Primärstudie erteilt. Die Ein- und Ausschlusskriterien entsprachen denen der Originalstudie und umfassten unter anderem volljährige Patienten mit histologisch bestätigtem Adenokarzinom des Rektums sowie eine durchgeführte Staging-MRT-Untersuchung inklusive kontrastmittelverstärkter T1-gewichteter Sequenzen. Ausgeschlossen wurden Patienten mit nicht-resektablen Tumoren oder Kontraindikationen gegen eine MRT-Untersuchung bzw. die Gabe von Gadolinium-basiertem Kontrastmittel. Für die aktuelle Analyse wurden alle Patienten des ursprünglichen Kollektivs berücksichtigt, bei denen eine vollständige Datenerfassung sowohl für das Avocado Sign als auch für die morphologischen T2-Kriterien aller detektierten mesorektalen Lymphknoten vorlag.",
            mriProtocol_title: "MRT-Protokoll und Bildakquisition",
            mriProtocol_content: "Alle MRT-Untersuchungen wurden an einem 3.0-Tesla-System (MAGNETOM Prisma Fit; Siemens Healthineers, Erlangen, Deutschland) unter Verwendung von Körper- und Wirbelsäulen-Array-Spulen durchgeführt. Das detaillierte MRT-Protokoll, inklusive spezifischer Sequenzparameter für die hochauflösenden T2-gewichteten (typische Schichtdicke für axiale T2w TSE für die Lymphknotenbeurteilung: {{T2_SCHICHTDICKE_MM}} mm) und kontrastmittelverstärkten T1-gewichteten Sequenzen, entsprach exakt dem in der initialen Avocado-Sign Studie publizierten Protokoll (Lurz M & Schäfer AO, Eur Radiol 2025, Tabelle 1). Kurz zusammengefasst, beinhaltete das Protokoll T2w-Turbo-Spin-Echo (TSE)-Sequenzen in sagittaler, axialer und koronarer Orientierung sowie axiale diffusionsgewichtete Bildgebung (DWI). Für die Evaluation des Avocado Signs wurden nach intravenöser Gabe eines Standard-Gadolinium-basierten Kontrastmittels (Gadoteridol; ProHance; Bracco Imaging Deutschland GmbH, Konstanz, Deutschland; 0.1 mmol/kg Körpergewicht) dynamische und/oder statische T1-gewichtete volumetrische Sequenzen mit spektraler Fettsättigung (z.B. VIBE Dixon-Technik) akquiriert. Zur Minimierung von Bewegungsartefakten wurde zu Beginn und bei Bedarf während der Untersuchung Butylscopolamin intravenös appliziert. Das Akquisitionsprotokoll war für das primäre Staging und das Restaging (nach nRCT) identisch.",
            imageAnalysis_title: "Bildanalyse",
            imageAnalysis_avocadoSign_content: "Die Bewertung des Avocado Signs (AS) erfolgte auf den kontrastmittelverstärkten T1-gewichteten Bildern mit Fettsättigung, wie in der Originalstudie detailliert beschrieben (Lurz M & Schäfer AO, Eur Radiol 2025). Das AS wurde als positiv (+) klassifiziert, wenn ein Lymphknoten einen sichtbaren, klar abgrenzbaren, signalarmen (hypointensen) Kern aufwies, der von einem ansonsten homogen signalreichen (hyperintensen, Kontrastmittel-aufnehmenden) Lymphknotenparenchym umgeben war – analog zum Kern einer Avocado. Alle anderen Erscheinungsformen, einschließlich homogen anreichernder, zystischer oder nekrotischer Lymphknoten ohne dieses spezifische Kern-Rind-Muster, wurden als negativ (-) für das AS gewertet. Die Beurteilung erfolgte für jeden einzelnen im Untersuchungsfeld sichtbaren mesorektalen Lymphknoten. Für die Klassifikation auf Patientenebene wurde ein Patient als AS-positiv eingestuft, wenn mindestens ein Lymphknoten das Avocado Sign zeigte.",
            imageAnalysis_t2Criteria_content: "Parallel zur AS-Bewertung wurden die morphologischen Eigenschaften aller im hochauflösenden T2w-MRT sichtbaren mesorektalen Lymphknoten systematisch erfasst. Diese Erfassung erfolgte bereits im Rahmen der Primärstudie und umfasste für jeden Lymphknoten: den maximalen Kurzachsendurchmesser (gemessen in Millimetern), die Form (kategorisiert als 'rund' oder 'oval'), die Kontur der Lymphknotengrenze (kategorisiert als 'scharf' bzw. glatt oder 'irregulär' bzw. spikuliert/unscharf), die Binnenstruktur bzw. Homogenität des Signals (kategorisiert als 'homogen' oder 'heterogen') und die Signalintensität relativ zur umgebenden Gesäßmuskulatur (kategorisiert als 'signalarm', 'intermediär' oder 'signalreich'). Diese detaillierten Merkmalserfassungen bildeten die Grundlage für die Anwendung der verschiedenen T2-Kriteriensets in der vorliegenden Analyse.",
            imageAnalysis_literatureT2Criteria_title: "Literatur-basierte T2-Kriteriensets",
            imageAnalysis_literatureT2Criteria_content: "Für den Vergleich mit dem Avocado Sign wurden drei etablierte T2-Kriteriensets aus der Literatur herangezogen. Die genauen Definitionen und Anwendungsmodalitäten sind in Tabelle {{TABLE_REF_LIT_T2_DEFINITIONS}} zusammengefasst. Kurzgefasst handelte es sich um:<br>1. <strong>Koh et al. (2008, Int J Radiat Oncol Biol Phys):</strong> Ein Lymphknoten wurde als suspekt gewertet, wenn er eine irreguläre Kontur ODER eine heterogene Binnenstruktur aufwies. Diese Kriterien wurden ursprünglich im Kontext des Restagings nach nRCT evaluiert, in dieser Studie jedoch explorativ auch auf das Primärstaging-Kollektiv angewendet.<br>2. <strong>Barbaro et al. (2024, Radiother Oncol):</strong> Diese Studie identifizierte einen optimalen Kurzachsendurchmesser-Cut-off von ≥ 2.3 mm als suspekt für Malignität im Restaging nach nRCT. Dieses Kriterium wurde daher spezifisch auf unsere nRCT-Subgruppe angewendet.<br>3. <strong>Rutegård et al. (2025, Eur Radiol) / ESGAR 2016 Kriterien:</strong> Dieses Set basiert auf den Konsensus-Empfehlungen der European Society of Gastrointestinal and Abdominal Radiology (ESGAR) von 2016 (Beets-Tan et al., 2018 Eur Radiol) für das Primärstaging. Ein Lymphknoten gilt hier als suspekt bei: (a) Kurzachse ≥ 9 mm; ODER (b) Kurzachse 5-8 mm UND ≥ 2 der folgenden morphologischen Merkmale: runde Form, irreguläre Kontur, heterogenes Signal; ODER (c) Kurzachse < 5 mm UND ALLE 3 der genannten morphologischen Merkmale. Diese Kriterien wurden primär auf die Direkt-OP-Gruppe (Primärstaging-Analog) und explorativ auf das Gesamtkollektiv angewendet.<br>Ein Patient wurde für ein gegebenes T2-Kriterienset als positiv (T2+) klassifiziert, wenn mindestens ein mesorektaler Lymphknoten die jeweiligen Suspektkriterien erfüllte.",
            imageAnalysis_bruteForceT2Criteria_title: "Brute-Force-Optimierung von T2-Kriterien",
            imageAnalysis_bruteForceT2Criteria_content: "Um die potenziell höchste diagnostische Leistung T2-basierter Kriterien auf unserem Datensatz zu ermitteln, wurde ein Brute-Force-Optimierungsalgorithmus eingesetzt. Dieser Algorithmus testete systematisch alle sinnvollen Permutationen der erfassten T2-Merkmale (Größe als Schwellenwert von {{T2_SIZE_MIN_BF}} mm bis {{T2_SIZE_MAX_BF}} mm in {{T2_SIZE_STEP_BF}} mm Schritten; Form ['rund', 'oval']; Kontur ['scharf', 'irregulär']; Homogenität ['homogen', 'heterogen']; Signal ['signalarm', 'intermediär', 'signalreich']) und deren logische Verknüpfung ('UND'-Logik: alle aktiven Kriterien müssen erfüllt sein; 'ODER'-Logik: mindestens ein aktives Kriterium muss erfüllt sein). Ziel der Optimierung war die Maximierung der Balanced Accuracy (alternativ AUC). Diese computergestützte Optimierung wurde separat für die Gesamtkohorte sowie für die Subgruppen 'Direkt OP' und 'nRCT' durchgeführt, um potenziell unterschiedliche optimale Kriteriensets für diese Kollektive zu identifizieren.",
            referenceStandard_title: "Histopathologischer Referenzstandard",
            referenceStandard_content: "Der definitive N-Status aller Patienten wurde durch die sorgfältige histopathologische Untersuchung der Operationspräparate nach totaler mesorektaler Exzision (TME) bestimmt. Die Resektate wurden standardisiert gemäß etablierten Protokollen aufgearbeitet. Alle im Mesorektum detektierten Lymphknoten wurden isoliert, gezählt und mikroskopisch auf das Vorhandensein von Tumorzellen untersucht. Ein Patient wurde als N-positiv (N+) klassifiziert, wenn mindestens ein Lymphknoten pathologisch als metastatisch befallen (pN+) bewertet wurde. Lagen in keinem der untersuchten Lymphknoten Metastasen vor, wurde der Patient als N-negativ (N- bzw. pN0) eingestuft. Diese histopathologische Klassifikation diente als Referenzstandard für alle Vergleiche der diagnostischen Güte.",
            statisticalAnalysis_title: "Statistische Analyse",
            statisticalAnalysis_content: "Die deskriptive Statistik umfasste die Berechnung von Medianen, Mittelwerten, Standardabweichungen (SD), Minima und Maxima für kontinuierliche Variablen sowie Häufigkeiten und Prozentanteile für kategoriale Daten. Die diagnostische Güte des Avocado Signs sowie der verschiedenen T2-Kriteriensets zur Vorhersage des pathologischen N-Status wurde anhand von Sensitivität, Spezifität, positivem prädiktivem Wert (PPV), negativem prädiktivem Wert (NPV), Gesamtgenauigkeit (Accuracy) und der Fläche unter der Receiver Operating Characteristic Kurve (AUC) – hier äquivalent zur Balanced Accuracy für binäre Tests – evaluiert. Für alle genannten Metriken wurden 95%-Konfidenzintervalle (CI) berechnet, wobei für Proportionen das Wilson-Score-Intervall und für AUC/Balanced Accuracy sowie den F1-Score die Bootstrap-Perzentil-Methode mit {{BOOTSTRAP_REPLICATIONS}} Replikationen verwendet wurde.<br>Der direkte statistische Vergleich der diagnostischen Leistung (Accuracy) zwischen dem Avocado Sign und den jeweiligen T2-Kriteriensets auf denselben Patienten erfolgte mittels des McNemar-Tests für gepaarte Daten. Unterschiede in den AUC-Werten wurden mit dem DeLong-Test für gepaarte ROC-Kurven analysiert. Assoziationen einzelner morphologischer T2-Merkmale (unabhängig von ihrer Verwendung in einem spezifischen Kriterienset) mit dem N-Status wurden explorativ mittels Odds Ratios (OR), Risk Differences (RD) und des Phi-Koeffizienten (φ) untersucht; die Signifikanz dieser Assoziationen wurde mittels Fisher's Exact Test (für kategoriale Merkmale) bzw. Mann-Whitney-U-Test (für kontinuierliche Merkmale wie Lymphknotengröße) bewertet.<br>Ein p-Wert von < {{SIGNIFICANCE_LEVEL}} wurde als statistisch signifikant definiert. Alle statistischen Analysen wurden unter Verwendung einer speziell für diese Studienreihe entwickelten, interaktiven Webanwendung (AvocadoSign-T2 Analyse Tool, Version {{APP_VERSION}}), die auf JavaScript (ES6+) und HTML/CSS basiert und die integrierten anonymisierten Studiendaten nutzt, durchgeführt."
        },
        en: {
            title: "Methods",
            introduction_title: "Introduction",
            introduction_content: "Accurate preoperative assessment of nodal status in patients with rectal cancer is crucial for determining the optimal treatment strategy and significantly influences prognosis. While magnetic resonance imaging (MRI) is the standard modality for local staging, reliable differentiation between benign and malignant mesorectal lymph nodes remains a challenge. Conventional morphological criteria based on T2-weighted (T2w) sequences often exhibit limited diagnostic accuracy. The Avocado Sign (AS), a novel contrast-enhanced MRI feature based on the specific enhancement pattern of lymph nodes in T1-weighted (T1w) sequences, demonstrated promising diagnostic performance for N-status prediction in an initial single-center study (Lurz M & Schäfer AO, Eur Radiol 2025; DOI: 10.1007/s00330-025-11462-y). The aim of the present study was to evaluate the diagnostic performance of the Avocado Sign in direct comparison with established T2w morphological criteria sets from the literature, as well as with data-driven, brute-force optimized T2w criteria, using the same well-characterized patient cohort.",
            studyPopulation_title: "Study Population and Data Collection",
            studyPopulation_content: "This retrospective analysis is based on the identical, prospectively evaluated patient cohort from the initial Avocado Sign study (Lurz M & Schäfer AO, Eur Radiol 2025). A total of {{PATIENT_COUNT_GESAMT}} consecutive patients with histologically confirmed rectal adenocarcinoma who underwent standardized preoperative pelvic MRI at Klinikum St. Georg, Leipzig, Germany, between January 2020 and November 2023 were included. Of these patients, {{PATIENT_COUNT_DIREKT_OP}} underwent upfront surgery without neoadjuvant therapy (upfront surgery group), while {{PATIENT_COUNT_NRCT}} patients received neoadjuvant chemoradiotherapy (nRCT group) followed by surgical resection. The retrospective analysis of pseudonymized patient and imaging data for this follow-up study was approved by the responsible ethics committee of Klinikum St. Georg Leipzig (Ethics Vote: {{ETHIK_VOTUM_NUMMER}}); all patients had previously provided written informed consent for the scientific use of their data within the primary study. Inclusion and exclusion criteria were identical to those of the original study and included adult patients with histologically confirmed rectal adenocarcinoma and a staging MRI examination including contrast-enhanced T1-weighted sequences. Patients with unresectable tumors or contraindications to MRI or gadolinium-based contrast agents were excluded. For the current analysis, all patients from the original cohort with complete data for both the Avocado Sign and morphological T2 criteria of all detected mesorectal lymph nodes were included.",
            mriProtocol_title: "MRI Protocol and Image Acquisition",
            mriProtocol_content: "All MRI examinations were performed on a 3.0-Tesla system (MAGNETOM Prisma Fit; Siemens Healthineers, Erlangen, Germany) using appropriate body and spine array coils. The detailed MRI protocol, including specific sequence parameters for high-resolution T2-weighted (typical slice thickness for axial T2w TSE for lymph node assessment: {{T2_SCHICHTDICKE_MM}} mm) and contrast-enhanced T1-weighted sequences, was identical to that published in the initial Avocado Sign study (Lurz M & Schäfer AO, Eur Radiol 2025, Table 1). Briefly, the protocol included T2w turbo spin-echo (TSE) sequences in sagittal, axial, and coronal orientations, as well as axial diffusion-weighted imaging (DWI). For the Avocado Sign evaluation, dynamic and/or static T1-weighted volumetric sequences with spectral fat saturation (e.g., VIBE Dixon technique) were acquired after intravenous administration of a weight-adapted macrocyclic gadolinium-based contrast agent (Gadoteridol; ProHance; Bracco Imaging Deutschland GmbH, Konstanz, Germany; 0.1 mmol/kg body weight). Butylscopolamine was administered intravenously at the beginning and, if necessary, during the examination to minimize motion artifacts. The acquisition protocol was identical for primary staging and restaging (after nRCT).",
            imageAnalysis_title: "Image Analysis",
            imageAnalysis_avocadoSign_content: "The Avocado Sign (AS) was assessed on contrast-enhanced T1-weighted, fat-suppressed images, as detailed in the original study (Lurz M & Schäfer AO, Eur Radiol 2025). The AS was rated positive (+) if a lymph node displayed a visible, clearly demarcated, hypointense core, surrounded by otherwise homogeneously hyperintense (contrast-enhancing) lymph node parenchyma, analogous to an avocado pit. All other appearances, including homogeneously enhancing, cystic, or necrotic lymph nodes without this specific core-rind pattern, were rated negative (-) for the AS. Assessment was performed for every visible mesorectal lymph node. For patient-level classification, a patient was considered AS-positive if at least one lymph node exhibited the Avocado Sign.",
            imageAnalysis_t2Criteria_content: "Concurrently with AS assessment, the morphological characteristics of all mesorectal lymph nodes visible on high-resolution T2w MRI were systematically recorded. This was done prospectively as part of the initial data collection and included, for each lymph node: maximum short-axis diameter (in mm), shape (categorized as 'round' or 'oval'), border contour (categorized as 'sharp'/'smooth' or 'irregular'/'spiculated/ill-defined'), internal signal homogeneity ('homogeneous' or 'heterogeneous'), and signal intensity relative to surrounding gluteal muscle ('signal-poor', 'intermediate', 'signal-rich'). This detailed feature extraction formed the basis for applying the various T2 criteria sets in the current study.",
            imageAnalysis_literatureT2Criteria_title: "Literature-Based T2 Criteria Sets",
            imageAnalysis_literatureT2Criteria_content: "For comparison with the Avocado Sign, three established T2 criteria sets from the literature were applied. Detailed definitions and application modalities are summarized in Table {{TABLE_REF_LIT_T2_DEFINITIONS}}. Briefly, these were:<br>1. <strong>Koh et al. (2008, Int J Radiat Oncol Biol Phys):</strong> A lymph node was considered suspicious if it exhibited an irregular border OR heterogeneous internal signal. These criteria were primarily evaluated in the context of restaging after nRCT in the original study but were exploratively applied to the primary staging cohort in this study.<br>2. <strong>Barbaro et al. (2024, Radiother Oncol):</strong> This study identified an optimal short-axis diameter cut-off of ≥ 2.3 mm as suspicious for malignant lymph nodes in restaging after nRCT. This criterion was therefore specifically applied to our nRCT subgroup.<br>3. <strong>Rutegård et al. (2025, Eur Radiol) / ESGAR 2016 Criteria:</strong> This set is based on the 2016 European Society of Gastrointestinal and Abdominal Radiology (ESGAR) consensus recommendations (Beets-Tan et al., 2018 Eur Radiol) for primary staging. A lymph node is considered suspicious if: (a) short-axis diameter ≥ 9 mm; OR (b) short-axis diameter 5-8 mm AND ≥ 2 of the following morphological features: round shape, irregular border, heterogeneous signal; OR (c) short-axis diameter < 5 mm AND ALL 3 of the mentioned morphological features. These criteria were primarily applied to the upfront surgery group (primary staging analogue) and exploratively to the overall cohort.<br>A patient was classified as T2-positive (T2+) for a given T2 criteria set if at least one mesorectal lymph node met the respective criteria for suspicion.",
            imageAnalysis_bruteForceT2Criteria_title: "Brute-Force Optimization of T2 Criteria",
            imageAnalysis_bruteForceT2Criteria_content: "To determine the potentially highest diagnostic performance of T2-based criteria on our dataset, a brute-force optimization algorithm was employed. This algorithm systematically tested all meaningful permutations of the recorded T2 features (size as a threshold from {{T2_SIZE_MIN_BF}} mm to {{T2_SIZE_MAX_BF}} mm in {{T2_SIZE_STEP_BF}} mm increments; shape ['round', 'oval']; border ['sharp', 'irregular']; homogeneity ['homogeneous', 'heterogeneous']; signal ['signal-poor', 'intermediate', 'signal-rich']) and their logical conjunction ('AND' logic: all active criteria must be met; 'OR' logic: at least one active criterion must be met). The primary target metric for maximization was Balanced Accuracy (alternatively AUC). This computational optimization was performed separately for the overall cohort and for the 'upfront surgery' and 'nRCT' subgroups to identify potentially different optimal criteria sets for these cohorts.",
            referenceStandard_title: "Histopathological Reference Standard",
            referenceStandard_content: "The definitive N-status for all patients was determined by meticulous histopathological examination of the surgical specimen after total mesorectal excision (TME). Resected specimens were processed according to established standard protocols. All detected lymph nodes within the mesorectum were isolated, counted, and microscopically assessed for the presence of tumor cells. A patient was classified as N-positive (N+) if at least one lymph node was pathologically confirmed as metastatic (pN+). If no metastases were found in any of the examined lymph nodes, the patient was classified as N-negative (N- or pN0). This histopathological classification served as the reference standard for all comparisons of diagnostic performance.",
            statisticalAnalysis_title: "Statistical Analysis",
            statisticalAnalysis_content: "Descriptive statistics included the calculation of medians, means, standard deviations (SD), minima, and maxima for continuous variables, and frequencies and percentages for categorical data. Diagnostic performance of the Avocado Sign and the various T2 criteria sets for predicting pathological N-status was evaluated using sensitivity, specificity, positive predictive value (PPV), negative predictive value (NPV), overall accuracy, and the area under the Receiver Operating Characteristic (ROC) curve (AUC)—equivalent to balanced accuracy for binary tests. 95% confidence intervals (CI) were calculated for all performance metrics, using the Wilson score interval for proportions and the bootstrap percentile method with {{BOOTSTRAP_REPLICATIONS}} replications for AUC/balanced accuracy and F1-score.<br>Direct statistical comparison of diagnostic performance (accuracy) between the Avocado Sign and the respective T2 criteria sets on the same patients was performed using McNemar's test for paired data. Differences in AUC values were assessed using DeLong's test for paired ROC curves. Associations of individual morphological T2 features (regardless of their activation in a specific criteria set) with N-status were exploratively investigated using Odds Ratios (OR), Risk Differences (RD), and the Phi coefficient (φ); p-values for these associations were calculated using Fisher's Exact Test (for categorical features) or the Mann-Whitney U test (for continuous features like lymph node size).<br>A p-value < {{SIGNIFICANCE_LEVEL}} was considered statistically significant. All statistical analyses were performed using a custom-developed interactive web application (AvocadoSign-T2 Analysis Tool, Version {{APP_VERSION}}), based on JavaScript (ES6+) and HTML/CSS, which utilized the integrated anonymized study data."
        }
    },
    ergebnisse: {
        de: {
            title: "Ergebnisse",
            cohortCharacteristics_title: "Charakteristika der Studienkohorte",
            cohortCharacteristics_content: "Insgesamt wurden {{PATIENT_COUNT_GESAMT}} Patienten ({{ANZAHL_MAENNLICH_GESAMT}} männlich ({{PROZENT_MAENNLICH_GESAMT}}%), {{ANZAHL_WEIBLICH_GESAMT}} weiblich ({{PROZENT_WEIBLICH_GESAMT}}%)) mit einem medianen Alter von {{ALTER_MEDIAN_GESAMT}} Jahren (Bereich: {{ALTER_MIN_GESAMT}}–{{ALTER_MAX_GESAMT}} Jahre) in die finale Analyse eingeschlossen. Von diesen erhielten {{PATIENT_COUNT_DIREKT_OP}} Patienten ({{PROZENT_DIREKT_OP}}%) eine primäre Operation (Direkt-OP-Gruppe) und {{PATIENT_COUNT_NRCT}} Patienten ({{PROZENT_NRCT}}%) eine neoadjuvante Radiochemotherapie (nRCT-Gruppe). Ein histopathologisch gesicherter Lymphknotenbefall (N+) lag bei {{ANZAHL_NPLUS_GESAMT}} von {{PATIENT_COUNT_GESAMT}} Patienten ({{PROZENT_NPLUS_GESAMT}}%) in der Gesamtkohorte vor. In der Direkt-OP-Gruppe waren dies {{ANZAHL_NPLUS_DIREKT_OP}} von {{PATIENT_COUNT_DIREKT_OP}} ({{PROZENT_NPLUS_DIREKT_OP}}%) und in der nRCT-Gruppe {{ANZAHL_NPLUS_NRCT}} von {{PATIENT_COUNT_NRCT}} Patienten ({{PROZENT_NPLUS_NRCT}}%). Die detaillierten Patientencharakteristika sind in Tabelle {{TABLE_REF_PAT_CHARS}} zusammengefasst.",
            avocadoSignPerformance_title: "Diagnostische Güte des Avocado Signs",
            avocadoSignPerformance_content: "Für das Gesamtkollektiv (N={{PATIENT_COUNT_GESAMT}}) zeigte das Avocado Sign (AS) eine Sensitivität von {{AS_SENS_GESAMT}} (95% CI {{AS_SENS_CI_LOW_GESAMT}}–{{AS_SENS_CI_HIGH_GESAMT}}), eine Spezifität von {{AS_SPEZ_GESAMT}} (95% CI {{AS_SPEZ_CI_LOW_GESAMT}}–{{AS_SPEZ_CI_HIGH_GESAMT}}) und eine Accuracy von {{AS_ACC_GESAMT}} (95% CI {{AS_ACC_CI_LOW_GESAMT}}–{{AS_ACC_CI_HIGH_GESAMT}}). Der positive prädiktive Wert (PPV) betrug {{AS_PPV_GESAMT}} (95% CI {{AS_PPV_CI_LOW_GESAMT}}–{{AS_PPV_CI_HIGH_GESAMT}}), der negative prädiktive Wert (NPV) {{AS_NPV_GESAMT}} (95% CI {{AS_NPV_CI_LOW_GESAMT}}–{{AS_NPV_CI_HIGH_GESAMT}}). Die Fläche unter der ROC-Kurve (AUC), äquivalent zur Balanced Accuracy, lag bei {{AS_AUC_GESAMT}} (95% CI {{AS_AUC_CI_LOW_GESAMT}}–{{AS_AUC_CI_HIGH_GESAMT}}).<br>In der Subgruppe der primär operierten Patienten (Direkt OP, N={{PATIENT_COUNT_DIREKT_OP}}) betrug die AUC {{AS_AUC_DIREKT_OP}} (95% CI {{AS_AUC_CI_DIREKT_OP_LOWER}}–{{AS_AUC_CI_DIREKT_OP_UPPER}}; Sensitivität {{AS_SENS_DIREKT_OP}}, Spezifität {{AS_SPEZ_DIREKT_OP}}).<br>In der nRCT-Subgruppe (N={{PATIENT_COUNT_NRCT}}) erreichte das AS eine AUC von {{AS_AUC_NRCT}} (95% CI {{AS_AUC_CI_NRCT_LOWER}}–{{AS_AUC_CI_NRCT_UPPER}}; Sensitivität {{AS_SENS_NRCT}}, Spezifität {{AS_SPEZ_NRCT}}). Die detaillierten Performance-Metriken für das Avocado Sign sind in Tabelle {{TABLE_REF_AS_PERFORMANCE}} und Abbildung {{FIG_REF_AS_PERFORMANCE_BARPLOT}} dargestellt.",
            t2CriteriaPerformance_title: "Diagnostische Güte der Literatur-basierten T2-Kriteriensets",
            t2CriteriaPerformance_intro_content: "Die diagnostische Güte der ausgewählten Literatur-basierten T2-Kriteriensets wurde jeweils auf dem passendsten Subkollektiv evaluiert. Die Ergebnisse sind in Tabelle {{TABLE_REF_LIT_T2_PERFORMANCE}} zusammengefasst.",
            t2CriteriaPerformance_koh_content: "Die Anwendung der Kriterien nach Koh et al. (irreguläre Kontur ODER heterogenes Binnensignal) auf die {{KOH_APPLICABLE_KOLLEKTIV_NAME}} (N={{KOH_PATIENT_COUNT}}) resultierte in einer AUC von {{KOH_AUC}} (95% CI {{KOH_AUC_CI_LOWER}}–{{KOH_AUC_CI_UPPER}}), einer Sensitivität von {{KOH_SENS}} und einer Spezifität von {{KOH_SPEZ}}.",
            t2CriteriaPerformance_barbaro_content: "Die Größenkriterien nach Barbaro et al. (Kurzachse ≥ 2.3 mm), spezifisch evaluiert in der {{BARBARO_APPLICABLE_KOLLEKTIV_NAME}} (N={{BARBARO_PATIENT_COUNT}}), erreichten eine AUC von {{BARBARO_AUC}} (95% CI {{BARBARO_AUC_CI_LOWER}}–{{BARBARO_AUC_CI_UPPER}}), eine Sensitivität von {{BARBARO_SENS}} und eine Spezifität von {{BARBARO_SPEZ}}.",
            t2CriteriaPerformance_rutegard_content: "Die ESGAR 2016 Kriterien (evaluiert durch Rutegård et al.), primär angewendet auf die {{RUTEGARD_APPLICABLE_KOLLEKTIV_NAME}} (N={{RUTEGARD_PATIENT_COUNT}}), zeigten eine AUC von {{RUTEGARD_AUC}} (95% CI {{RUTEGARD_AUC_CI_LOWER}}–{{RUTEGARD_AUC_CI_UPPER}}), eine Sensitivität von {{RUTEGARD_SENS}} und eine Spezifität von {{RUTEGARD_SPEZ}}.",
            bruteForceOptimalT2_title: "Diagnostische Güte der Brute-Force-optimierten T2-Kriteriensets",
            bruteForceOptimalT2_content: "Die mittels Brute-Force-Analyse für die Maximierung der Balanced Accuracy/AUC identifizierten T2-Kriteriensets und deren diagnostische Güte sind in Tabelle {{TABLE_REF_BF_T2_PERFORMANCE}} dargestellt. Für das **Gesamtkollektiv** (N={{BF_GESAMT_N}}) wurde mit den Kriterien '{{BF_GESAMT_KRITERIEN_TEXT}}' (Logik: {{BF_GESAMT_LOGIC_OPERATOR}}) eine AUC von {{BF_AUC_GESAMT}} (95% CI {{BF_AUC_CI_GESAMT_LOWER}}–{{BF_AUC_CI_HIGH_GESAMT}}; Sensitivität {{BF_SENS_GESAMT}}, Spezifität {{BF_SPEZ_GESAMT}}) erreicht.<br>Für die **Direkt-OP-Gruppe** (N={{BF_DIREKT_OP_N}}) lauteten die optimierten Kriterien '{{BF_DIREKT_OP_KRITERIEN_TEXT}}' (Logik: {{BF_DIREKT_OP_LOGIC_OPERATOR}}) und erzielten eine AUC von {{BF_AUC_DIREKT_OP}} (95% CI ...; Sens. {{BF_SENS_DIREKT_OP}}, Spez. {{BF_SPEZ_DIREKT_OP}}).<br>In der **nRCT-Gruppe** (N={{BF_NRCT_N}}) waren dies '{{BF_NRCT_KRITERIEN_TEXT}}' (Logik: {{BF_NRCT_LOGIC_OPERATOR}}) mit einer AUC von {{BF_AUC_NRCT}} (95% CI ...; Sens. {{BF_SENS_NRCT}}, Spez. {{BF_SPEZ_NRCT}}). [FALLS_BF_NICHT_VERFUEGBAR_TEXT]",
            comparisonAsVsT2_title: "Direkter statistischer Vergleich: Avocado Sign vs. T2-Kriteriensets",
            comparisonAsVsT2_content: "Die Ergebnisse der statistischen Vergleiche (DeLong-Test für AUC, McNemar-Test für Accuracy) zwischen dem Avocado Sign und den verschiedenen T2-Kriteriensets sind in Tabelle {{TABLE_REF_AS_VS_LIT_T2_COMPARISON}} (für Literatur-Kriterien) und Tabelle {{TABLE_REF_AS_VS_BF_T2_COMPARISON}} (für Brute-Force-optimierte Kriterien) detailliert aufgeführt.<br>Gegenüber den Koh-Kriterien (Gesamtkollektiv) zeigte das AS eine {{AS_VS_KOH_AUC_DIRECTION}} AUC (p={{AS_VS_KOH_P_DELONG}}) und eine {{AS_VS_KOH_ACC_DIRECTION}} Accuracy (p={{AS_VS_KOH_P_MCNEMAR}}).<br>Im Vergleich zu den Barbaro-Kriterien (nRCT-Gruppe) war die AUC des AS {{AS_VS_BARBARO_AUC_DIRECTION}} (p={{AS_VS_BARBARO_P_DELONG}}), die Accuracy {{AS_VS_BARBARO_ACC_DIRECTION}} (p={{AS_VS_BARBARO_P_MCNEMAR}}).<br>Gegenüber den ESGAR 2016 Kriterien (Direkt-OP-Gruppe) war die AUC des AS {{AS_VS_RUTEGARD_AUC_DIRECTION}} (p={{AS_VS_RUTEGARD_P_DELONG}}), die Accuracy {{AS_VS_RUTEGARD_ACC_DIRECTION}} (p={{AS_VS_RUTEGARD_P_MCNEMAR}}).<br>Verglichen mit den jeweils für die Balanced Accuracy/AUC optimierten T2-Kriterien war die AUC des AS für das Gesamtkollektiv {{AS_VS_BF_AUC_DIRECTION_GESAMT}} (p={{AS_VS_BF_P_DELONG_GESAMT}}), für die Direkt-OP-Gruppe {{AS_VS_BF_AUC_DIRECTION_DIREKT_OP}} (p={{AS_VS_BF_P_DELONG_DIREKT_OP}}) und für die nRCT-Gruppe {{AS_VS_BF_AUC_DIRECTION_NRCT}} (p={{AS_VS_BF_P_DELONG_NRCT}}).<br>Vergleichende ROC-Kurven für das Gesamtkollektiv sind in Abbildung {{FIG_REF_ROC_COMPARISON}} und ein Vergleich ausgewählter Schlüsselmetriken für alle Kollektive in Abbildung {{FIG_REF_METRIC_COMPARISON_BARCHART}} dargestellt."
        },
        en: {
            title: "Results",
            cohortCharacteristics_title: "Cohort Characteristics",
            cohortCharacteristics_content: "A total of {{PATIENT_COUNT_GESAMT}} patients ({{ANZAHL_MAENNLICH_GESAMT}} male ({{PROZENT_MAENNLICH_GESAMT}}%), {{ANZAHL_WEIBLICH_GESAMT}} female ({{PROZENT_WEIBLICH_GESAMT}}%)) with a median age of {{ALTER_MEDIAN_GESAMT}} years (range: {{ALTER_MIN_GESAMT}}–{{ALTER_MAX_GESAMT}} years) were included in the final analysis. Of these, {{PATIENT_COUNT_DIREKT_OP}} patients ({{PROZENT_DIREKT_OP}}%) underwent upfront surgery (upfront surgery group) and {{PATIENT_COUNT_NRCT}} patients ({{PROZENT_NRCT}}%) received neoadjuvant chemoradiotherapy (nRCT group). Histopathologically confirmed lymph node involvement (N+) was present in {{ANZAHL_NPLUS_GESAMT}} of {{PATIENT_COUNT_GESAMT}} patients ({{PROZENT_NPLUS_GESAMT}}%) in the overall cohort. In the upfront surgery group, {{ANZAHL_NPLUS_DIREKT_OP}} of {{PATIENT_COUNT_DIREKT_OP}} ({{PROZENT_NPLUS_DIREKT_OP}}%) were N+, and in the nRCT group, {{ANZAHL_NPLUS_NRCT}} of {{PATIENT_COUNT_NRCT}} patients ({{PROZENT_NPLUS_NRCT}}%) were N+. Detailed patient characteristics are summarized in Table {{TABLE_REF_PAT_CHARS}}.",
            avocadoSignPerformance_title: "Diagnostic Performance of the Avocado Sign",
            avocadoSignPerformance_content: "For the overall cohort (N={{PATIENT_COUNT_GESAMT}}), the Avocado Sign (AS) achieved an AUC of {{AS_AUC_GESAMT}} (95% CI {{AS_AUC_CI_GESAMT_LOWER}}–{{AS_AUC_CI_GESAMT_UPPER}}) for predicting N-status, with an accuracy of {{AS_ACC_GESAMT}} (95% CI {{AS_ACC_CI_GESAMT_LOWER}}–{{AS_ACC_CI_GESAMT_UPPER}}), sensitivity of {{AS_SENS_GESAMT}} (95% CI {{AS_SENS_CI_LOW_GESAMT}}–{{AS_SENS_CI_HIGH_GESAMT}}), and specificity of {{AS_SPEZ_GESAMT}} (95% CI {{AS_SPEZ_CI_LOW_GESAMT}}–{{AS_SPEZ_CI_HIGH_GESAMT}}). The PPV was {{AS_PPV_GESAMT}} (95% CI {{AS_PPV_CI_LOW_GESAMT}}–{{AS_PPV_CI_HIGH_GESAMT}}), and the NPV was {{AS_NPV_GESAMT}} (95% CI {{AS_NPV_CI_LOW_GESAMT}}–{{AS_NPV_CI_HIGH_GESAMT}}).<br>In the upfront surgery subgroup (N={{PATIENT_COUNT_DIREKT_OP}}), the AUC was {{AS_AUC_DIREKT_OP}} (95% CI {{AS_AUC_CI_DIREKT_OP_LOWER}}–{{AS_AUC_CI_DIREKT_OP_UPPER}}; sensitivity {{AS_SENS_DIREKT_OP}}, specificity {{AS_SPEZ_DIREKT_OP}}).<br>In the nRCT subgroup (N={{PATIENT_COUNT_NRCT}}), the AS achieved an AUC of {{AS_AUC_NRCT}} (95% CI {{AS_AUC_CI_NRCT_LOWER}}–{{AS_AUC_CI_NRCT_UPPER}}; sensitivity {{AS_SENS_NRCT}}, specificity {{AS_SPEZ_NRCT}}). Detailed performance metrics for the Avocado Sign are presented in Table {{TABLE_REF_AS_PERFORMANCE}} and Figure {{FIG_REF_AS_PERFORMANCE_BARPLOT}}.",
            t2CriteriaPerformance_title: "Diagnostic Performance of Literature-Based T2 Criteria Sets",
            t2CriteriaPerformance_intro_content: "The diagnostic performance of the selected literature-based T2 criteria sets was evaluated on the most appropriate sub-cohort for each set. The results are summarized in Table {{TABLE_REF_LIT_T2_PERFORMANCE}}.",
            t2CriteriaPerformance_koh_content: "Applying the criteria by Koh et al. (irregular border OR heterogeneous internal signal) to the {{KOH_APPLICABLE_KOLLEKTIV_NAME}} (N={{KOH_PATIENT_COUNT}}) resulted in an AUC of {{KOH_AUC}} (95% CI {{KOH_AUC_CI_LOWER}}–{{KOH_AUC_CI_UPPER}}), a sensitivity of {{KOH_SENS}}, and a specificity of {{KOH_SPEZ}}.",
            t2CriteriaPerformance_barbaro_content: "The size criteria by Barbaro et al. (short-axis ≥ 2.3 mm), specifically evaluated in the {{BARBARO_APPLICABLE_KOLLEKTIV_NAME}} (N={{BARBARO_PATIENT_COUNT}}), achieved an AUC of {{BARBARO_AUC}} (95% CI {{BARBARO_AUC_CI_LOWER}}–{{BARBARO_AUC_CI_UPPER}}), a sensitivity of {{BARBARO_SENS}}, and a specificity of {{BARBARO_SPEZ}}.",
            t2CriteriaPerformance_rutegard_content: "The ESGAR 2016 criteria (evaluated by Rutegård et al.), primarily applied to the {{RUTEGARD_APPLICABLE_KOLLEKTIV_NAME}} (N={{RUTEGARD_PATIENT_COUNT}}), showed an AUC of {{RUTEGARD_AUC}} (95% CI {{RUTEGARD_AUC_CI_LOWER}}–{{RUTEGARD_AUC_CI_UPPER}}), a sensitivity of {{RUTEGARD_SENS}}, and a specificity of {{RUTEGARD_SPEZ}}.",
            bruteForceOptimalT2_title: "Diagnostic Performance of Brute-Force Optimized T2 Criteria Sets",
            bruteForceOptimalT2_content: "The T2 criteria sets identified by brute-force optimization to maximize Balanced Accuracy/AUC and their diagnostic performance are shown in Table {{TABLE_REF_BF_T2_PERFORMANCE}}. For the **overall cohort** (N={{BF_GESAMT_N}}), the optimized criteria '{{BF_GESAMT_KRITERIEN_TEXT}}' (logic: {{BF_GESAMT_LOGIC_OPERATOR}}) achieved an AUC of {{BF_AUC_GESAMT}} (95% CI {{BF_AUC_CI_GESAMT_LOWER}}–{{BF_AUC_CI_HIGH_GESAMT}}; sensitivity {{BF_SENS_GESAMT}}, specificity {{BF_SPEZ_GESAMT}}).<br>For the **upfront surgery group** (N={{BF_DIREKT_OP_N}}), the optimized criteria were '{{BF_DIREKT_OP_KRITERIEN_TEXT}}' (logic: {{BF_DIREKT_OP_LOGIC_OPERATOR}}), yielding an AUC of {{BF_AUC_DIREKT_OP}} (95% CI ...; sens. {{BF_SENS_DIREKT_OP}}, spec. {{BF_SPEZ_DIREKT_OP}}).<br>In the **nRCT group** (N={{BF_NRCT_N}}), the best criteria were '{{BF_NRCT_KRITERIEN_TEXT}}' (logic: {{BF_NRCT_LOGIC_OPERATOR}}), with an AUC of {{BF_AUC_NRCT}} (95% CI ...; sens. {{BF_SENS_NRCT}}, spec. {{BF_SPEZ_NRCT}}). [FALLS_BF_NICHT_VERFUEGBAR_TEXT]",
            comparisonAsVsT2_title: "Direct Statistical Comparison: Avocado Sign vs. T2 Criteria Sets",
            comparisonAsVsT2_content: "The results of statistical comparisons (DeLong test for AUC, McNemar test for Accuracy) between the Avocado Sign and the various T2 criteria sets are detailed in Table {{TABLE_REF_AS_VS_LIT_T2_COMPARISON}} (for literature criteria) and Table {{TABLE_REF_AS_VS_BF_T2_COMPARISON}} (for brute-force optimized criteria).<br>Compared to the Koh et al. criteria (overall cohort), the AS showed {{AS_VS_KOH_AUC_DIRECTION}} AUC (p={{AS_VS_KOH_P_DELONG}}) and {{AS_VS_KOH_ACC_DIRECTION}} accuracy (p={{AS_VS_KOH_P_MCNEMAR}}).<br>Against the Barbaro criteria (nRCT subgroup), the AS had {{AS_VS_BARBARO_AUC_DIRECTION}} AUC (p={{AS_VS_BARBARO_P_DELONG}}) and {{AS_VS_BARBARO_ACC_DIRECTION}} accuracy (p={{AS_VS_BARBARO_P_MCNEMAR}}).<br>Versus the ESGAR 2016 criteria (upfront surgery group), the AS demonstrated {{AS_VS_RUTEGARD_AUC_DIRECTION}} AUC (p={{AS_VS_RUTEGARD_P_DELONG}}) and {{AS_VS_RUTEGARD_ACC_DIRECTION}} accuracy (p={{AS_VS_RUTEGARD_P_MCNEMAR}}).<br>When compared to the respective T2 criteria optimized for Balanced Accuracy/AUC, the AUC of the AS for the overall cohort was {{AS_VS_BF_AUC_DIRECTION_GESAMT}} (p={{AS_VS_BF_P_DELONG_GESAMT}}), for the upfront surgery group {{AS_VS_BF_AUC_DIRECTION_DIREKT_OP}} (p={{AS_VS_BF_P_DELONG_DIREKT_OP}}), and for the nRCT group {{AS_VS_BF_AUC_DIRECTION_NRCT}} (p={{AS_VS_BF_P_DELONG_NRCT}}).<br>Comparative ROC curves for the overall cohort are shown in Figure {{FIG_REF_ROC_COMPARISON}}, and a comparison of key metrics across all cohorts is depicted in Figure {{FIG_REF_METRIC_COMPARISON_BARCHART}}."
        }
    }
};

deepFreeze(PUBLICATION_TEXTS);