const PUBLICATION_TEXT_TEMPLATES = {
    de: {
        methoden: {
            methoden_studienanlage: `
                <p>Diese Studie wurde als retrospektive Analyse eines prospektiv geführten, monozentrischen Patientenkollektivs mit histologisch gesichertem Rektumkarzinom durchgeführt. Die primäre Studienpopulation und die zugrundeliegenden Bilddatensätze für die initiale Bewertung des Avocado Signs (AS) sind mit denen der Originalpublikation zum Avocado Sign von Lurz & Schäfer (2025) [{STUDY_REF_AVOCADO_SIGN}] identisch. Ziel dieser erweiterten Untersuchung ist der detaillierte Vergleich der diagnostischen Güte des AS mit etablierten und optimierten T2-gewichteten morphologischen Kriterien zur Prädiktion des mesorektalen Lymphknotenstatus (N-Status) sowie die Bereitstellung eines explorativen Werkzeugs für weiterführende Analysen.</p>
                <p>Alle hier präsentierten Analysen und Kriterienevaluationen wurden mittels einer interaktiven Webanwendung ({APP_NAME} v{APP_VERSION}) durchgeführt, die eigens für diese und nachfolgende Studien entwickelt wurde. Dieses Werkzeug ermöglicht die flexible Definition und Anwendung von T2-Kriteriensets, eine automatisierte Optimierung von Kriterienkombinationen sowie eine umfassende statistische Auswertung und Visualisierung der Ergebnisse. Die Studie wurde in Übereinstimmung mit den Grundsätzen der Deklaration von Helsinki durchgeführt. Das Studienprotokoll wurde von der lokalen Ethikkommission (Ethikkommission der Sächsischen Landesärztekammer, Votum Nr. {ETHICS_VOTE_NUMBER}) genehmigt. Aufgrund des retrospektiven Charakters der Analyse auf pseudonymisierten Daten wurde von der Ethikkommission auf ein erneutes Einholen eines schriftlichen Einverständnisses der Patienten für diese spezifische erweiterte Auswertung verzichtet, da ein generelles Einverständnis zur wissenschaftlichen Auswertung im Rahmen der Primärstudie vorlag.</p>
            `,
            methoden_patientenkollektiv: `
                <p>Das Studienkollektiv umfasste {N_GESAMT} konsekutive Patienten mit histologisch gesichertem Rektumkarzinom, die zwischen {STUDY_PERIOD} am Klinikum St. Georg, Leipzig, behandelt und in die initiale Avocado-Sign-Studie [{STUDY_REF_AVOCADO_SIGN}] eingeschlossen wurden. Von diesen erhielten {N_NRCT} Patienten eine neoadjuvante Radiochemotherapie (nRCT-Gruppe), während {N_DIREKT_OP} Patienten primär operiert wurden (Direkt-OP-Gruppe). Das mediane Alter im Gesamtkollektiv betrug {MEDIAN_AGE_GESAMT} Jahre (Range: {MIN_AGE_GESAMT}–{MAX_AGE_GESAMT} Jahre), und {PERCENT_MALE_GESAMT}% ({N_MALE_GESAMT}/{N_GESAMT}) der Patienten waren männlich. Detaillierte Patientencharakteristika, stratifiziert nach Behandlungsgruppen, sind in <a href="{TABLE_PATIENT_CHARACTERISTICS_REF_LINK}">Tabelle 1</a> dargestellt.</p>
                <p>Die Einschlusskriterien für die Primärstudie waren ein Alter von mindestens 18 Jahren und ein histologisch bestätigtes Rektumkarzinom. Ausschlusskriterien umfassten nicht resektable Tumoren und Kontraindikationen für eine MRT-Untersuchung. Für die vorliegende erweiterte Analyse wurden alle Patienten der Primärstudie berücksichtigt, für die vollständige Datensätze bezüglich der T1KM- und T2-Lymphknotenmerkmale vorlagen.</p>
            `,
            methoden_mrt_protokoll: `
                <p>Alle MRT-Untersuchungen wurden an einem {MRT_SYSTEM} unter Verwendung von Körper- und Wirbelsäulen-Array-Spulen durchgeführt. Das standardisierte Bildgebungsprotokoll umfasste hochauflösende T2-gewichtete Turbo-Spin-Echo (TSE)-Sequenzen in sagittaler, axialer und koronarer Ebene (Schichtdicke {T2_SLICE_THICKNESS}) sowie eine axiale diffusionsgewichtete Sequenz (DWI). Für die Bewertung des Avocado Signs wurde, wie in der Primärstudie [{STUDY_REF_AVOCADO_SIGN}] beschrieben, eine kontrastmittelverstärkte axiale T1-gewichtete volumetrische interpolierte Breath-Hold-Sequenz (VIBE) mit Dixon-Fettunterdrückung akquiriert.</p>
                <p>Ein makrozyklisches Gadolinium-basiertes Kontrastmittel ({CONTRAST_AGENT_AS}) wurde gewichtsadaptiert (0,2 ml/kg Körpergewicht) intravenös verabreicht. Die kontrastmittelverstärkten Aufnahmen erfolgten unmittelbar nach vollständiger Applikation des Kontrastmittels. Butylscopolamin wurde zur Reduktion von Bewegungsartefakten appliziert. Das Bildgebungsprotokoll war für die primäre Staging-Untersuchung und die Restaging-Untersuchung (bei Patienten der nRCT-Gruppe) identisch.</p>
            `,
            methoden_as_definition: `
                <p>Das Avocado Sign wurde, wie in der Originalstudie [{STUDY_REF_AVOCADO_SIGN}] definiert, auf den kontrastmittelverstärkten T1-gewichteten Bildern evaluiert. Es ist charakterisiert als ein klar abgrenzbarer, hypointenser Kern innerhalb eines ansonsten homogen hyperintensen Lymphknotens, unabhängig von dessen Größe oder Form (siehe Abbildung 2 in [{STUDY_REF_AVOCADO_SIGN}]). Die Bewertung erfolgte für alle im T1KM-MRT sichtbaren mesorektalen Lymphknoten. Ein Patient wurde als Avocado-Sign-positiv (AS+) eingestuft, wenn mindestens ein Lymphknoten dieses Zeichen aufwies. Die Bildanalyse wurde von zwei Radiologen (Erfahrung: {RADIOLOGIST_EXPERIENCE_1} bzw. {RADIOLOGIST_EXPERIENCE_2} Jahre in der abdominellen MRT), die bereits die Primärstudie durchführten, unabhängig und verblindet gegenüber den histopathologischen Ergebnissen und den T2-Merkmalen vorgenommen. Diskrepanzen wurden im Konsens mit einem dritten, ebenfalls erfahrenen Radiologen (Erfahrung: {RADIOLOGIST_EXPERIENCE_3} Jahre) gelöst. Für Patienten der nRCT-Gruppe erfolgte die AS-Bewertung auf den Restaging-MRT-Bildern.</p>
            `,
            methoden_t2_definition: `
                <p>Die morphologischen T2-gewichteten Kriterien (Größe [Kurzachse in mm], Form ['rund', 'oval'], Kontur ['scharf', 'irregulär'], Homogenität ['homogen', 'heterogen'] und Signalintensität ['signalarm', 'intermediär', 'signalreich']) wurden für jeden im hochauflösenden T2w-MRT sichtbaren mesorektalen Lymphknoten von denselben zwei Radiologen erfasst, die auch das Avocado Sign bewerteten. Die Bewertung erfolgte konsensbasiert und verblindet gegenüber dem pathologischen N-Status und dem Avocado-Sign-Status.</p>
                <p>Für den Vergleich der diagnostischen Güte wurden folgende T2-Kriteriensets herangezogen:</p>
                <ol>
                    <li><strong>Literatur-basierte T2-Kriteriensets:</strong> Eine Auswahl etablierter Kriterien aus der Fachliteratur wurde implementiert und auf die entsprechenden Subgruppen bzw. das Gesamtkollektiv unseres Datensatzes angewendet (Details siehe <a href="{TABLE_LITERATURE_T2_CRITERIA_REF_LINK}">Tabelle 2</a>):
                        <ul>
                            <li>Koh et al. (2008) [{STUDY_REF_KOH_2008}]: Definiert als "${KOH_2008_DEFINITION}". Dieses Set wurde in unserer Analyse auf das Kollektiv '${KOH_2008_APPLICABLE_KOLLEKTIV}' angewendet.</li>
                            <li>Barbaro et al. (2024) [{STUDY_REF_BARBARO_2024}]: Definiert als "${BARBARO_2024_DEFINITION}". Dieses Set wurde spezifisch für das Kollektiv '${BARBARO_2024_APPLICABLE_KOLLEKTIV}' (Restaging) evaluiert.</li>
                            <li>ESGAR Konsensus Kriterien (Beets-Tan et al., 2018 [{STUDY_REF_ESGAR_2018}]), evaluiert durch Rutegård et al. (2025) [{STUDY_REF_RUTEGARD_2025}]: Definiert als "${ESGAR_2016_RUTEGARD_2025_DEFINITION}". Dieses Set wurde primär auf das Kollektiv '${ESGAR_2016_RUTEGARD_2025_APPLICABLE_KOLLEKTIV}' (Primärstaging) angewendet.</li>
                        </ul>
                    </li>
                    <li><strong>Brute-Force optimierte T2-Kriterien:</strong> Mittels eines im Analyse-Tool implementierten Brute-Force-Algorithmus wurden für jedes der drei Hauptkollektive (Gesamt, Direkt OP, nRCT) diejenigen Kombinationen aus den fünf T2-Merkmalen und einer UND/ODER-Logik identifiziert, welche die primäre Zielmetrik dieser Studie – die <strong>{BF_TARGET_METRIC_NAME}</strong> – maximieren. Die resultierenden, für jedes Kollektiv spezifisch optimierten Kriteriensets waren:
                        <ul>
                            <li><strong>Gesamtkollektiv:</strong> {BF_OPTIMIZED_GESAMT_DEFINITION} (Zielmetrik: {BF_TARGET_METRIC_NAME}, Wert: {BF_OPTIMIZED_GESAMT_VALUE})</li>
                            <li><strong>Direkt-OP Kollektiv:</strong> {BF_OPTIMIZED_DIREKT_OP_DEFINITION} (Zielmetrik: {BF_TARGET_METRIC_NAME}, Wert: {BF_OPTIMIZED_DIREKT_OP_VALUE})</li>
                            <li><strong>nRCT Kollektiv:</strong> {BF_OPTIMIZED_NRCT_DEFINITION} (Zielmetrik: {BF_TARGET_METRIC_NAME}, Wert: {BF_OPTIMIZED_NRCT_VALUE})</li>
                        </ul>
                    </li>
                    <li><strong>Im Analyse-Tool aktuell eingestellte T2-Kriterien:</strong> Die aktuell im Tool eingestellten Kriterien zum Zeitpunkt der finalen Analyse waren: {APPLIED_T2_CRITERIA_STRING}. Diese dienten primär als Referenzpunkt für explorative Analysen und zur Demonstration der Flexibilität des Werkzeugs.</li>
                </ol>
                <p>Ein Lymphknoten wurde als T2-positiv für ein gegebenes Kriterienset gewertet, wenn er die spezifischen Bedingungen dieses Sets erfüllte. Ein Patient galt als T2-positiv, wenn mindestens ein Lymphknoten gemäß dem jeweiligen Kriterienset als positiv bewertet wurde.</p>
            `,
            methoden_referenzstandard: `
                <p>Die histopathologische Untersuchung der Operationspräparate nach totaler mesorektaler Exzision (TME) diente als Referenzstandard für den Lymphknotenstatus. Alle mesorektalen Lymphknoten wurden von erfahrenen Pathologen gemäß den etablierten Standardprotokollen aufgearbeitet und mikroskopisch bewertet. Der N-Status eines Patienten wurde als positiv (N+) definiert, wenn mindestens ein Lymphknoten histologisch als metastatisch befallen identifiziert wurde. Andernfalls galt der Patient als N-negativ (N0).</p>
            `,
            methoden_statistische_analyse: `
                <p>Die deskriptive Statistik umfasste die Berechnung von Medianen, Mittelwerten, Standardabweichungen (SD), Minima und Maxima für kontinuierliche Variablen sowie absolute Häufigkeiten und Prozentanteile für kategoriale Daten. Die diagnostische Güte des Avocado Signs sowie der verschiedenen T2-Kriteriensets (Literatur-basiert und Brute-Force-optimiert) wurde anhand von Sensitivität, Spezifität, positivem prädiktiven Wert (PPV), negativem prädiktiven Wert (NPV), Accuracy (ACC), Balanced Accuracy (BalAcc) und der Fläche unter der Receiver Operating Characteristic-Kurve (AUC) – bei binären Tests äquivalent zur BalAcc – evaluiert. Für diese Metriken wurden zweiseitige 95%-Konfidenzintervalle (KI) berechnet. Für Proportionen (Sensitivität, Spezifität, PPV, NPV, Accuracy) wurde die ${CI_METHOD_PROPORTION}-Methode verwendet. Für BalAcc (AUC) und den F1-Score wurde die ${CI_METHOD_EFFECTSIZE}-Methode mit ${BOOTSTRAP_REPLICATIONS} Replikationen angewendet.</p>
                <p>Der statistische Vergleich der diagnostischen Leistung (Accuracy, AUC) zwischen dem Avocado Sign und den jeweiligen T2-Kriteriensets innerhalb derselben Patientengruppe (gepaarte Daten) erfolgte mittels des McNemar-Tests für gepaarte nominale Daten bzw. des DeLong-Tests für den Vergleich von AUC-Werten. Der Vergleich von Performance-Metriken zwischen unabhängigen Kollektiven (z.B. Direkt-OP vs. nRCT-Gruppe) erfolgte mittels Fisher's Exact Test für Raten (wie Accuracy) und mittels Z-Test für den Vergleich von AUC-Werten basierend auf deren Bootstrap-Standardfehlern. Odds Ratios (OR) und Risk Differences (RD) wurden zur Quantifizierung von Assoziationen berechnet, ebenfalls mit 95%-KI. Der Phi-Koeffizient (φ) wurde als Maß für die Stärke des Zusammenhangs zwischen binären Merkmalen herangezogen. Für den Vergleich von Verteilungen kontinuierlicher Variablen zwischen zwei unabhängigen Gruppen wurde der Mann-Whitney-U-Test verwendet. Ein p-Wert < ${ALPHA_LEVEL_TEXT} wurde als statistisch signifikant interpretiert. Alle statistischen Analysen wurden mit der oben genannten, speziell entwickelten Webanwendung ({APP_NAME} v{APP_VERSION}) durchgeführt, die auf Standardbibliotheken für statistische Berechnungen und JavaScript basiert.</p>
            `
        },
        ergebnisse: {
            ergebnisse_patientencharakteristika: `
                <p>Die Charakteristika der {N_GESAMT} in die Studie eingeschlossenen Patienten sind in <a href="{TABLE_PATIENT_CHARACTERISTICS_REF_LINK}">Tabelle 1</a> zusammengefasst und entsprechen den Daten der initialen Avocado-Sign-Studie [{STUDY_REF_AVOCADO_SIGN}]. Das Gesamtkollektiv bestand aus {N_DIREKT_OP} Patienten, die primär operiert wurden (Direkt-OP-Gruppe), und {N_NRCT} Patienten, die eine neoadjuvante Radiochemotherapie erhielten (nRCT-Gruppe). Das mediane Alter im Gesamtkollektiv betrug {MEDIAN_AGE_GESAMT} Jahre (Range {MIN_AGE_GESAMT}–{MAX_AGE_GESAMT}), und {PERCENT_MALE_GESAMT}% waren männlich. Ein histopathologisch gesicherter positiver Lymphknotenstatus (N+) fand sich bei {N_PLUS_GESAMT} von {N_GESAMT} Patienten ({PERCENT_N_PLUS_GESAMT}%) im Gesamtkollektiv. Die Verteilung von Alter und Geschlecht im Gesamtkollektiv ist in <a href="{FIG_AGE_DISTRIBUTION_REF_LINK}">Abbildung 1a</a> und <a href="{FIG_GENDER_DISTRIBUTION_REF_LINK}">Abbildung 1b</a> dargestellt.</p>
            `,
            ergebnisse_as_performance: `
                <p>Die diagnostische Güte des Avocado Signs (AS) zur Vorhersage des pathologischen N-Status ist für das Gesamtkollektiv und die Subgruppen in <a href="{TABLE_AS_PERFORMANCE_REF_LINK}">Tabelle 3</a> detailliert aufgeführt. Im Gesamtkollektiv (${KOLLEKTIV_TEXT_GESAMT}) erreichte das AS eine Sensitivität von {AS_SENS_GESAMT_CI}, eine Spezifität von {AS_SPEZ_GESAMT_CI}, einen positiven prädiktiven Wert (PPV) von {AS_PPV_GESAMT_CI}, einen negativen prädiktiven Wert (NPV) von {AS_NPV_GESAMT_CI} und eine Accuracy von {AS_ACC_GESAMT_CI}. Die AUC (Balanced Accuracy) betrug {AS_AUC_GESAMT_CI}.</p>
                <p>In der Subgruppe der primär operierten Patienten (Direkt-OP-Gruppe, ${KOLLEKTIV_TEXT_DIREKT_OP}) zeigte das AS eine Sensitivität von {AS_SENS_DIREKT_OP_CI} und eine Spezifität von {AS_SPEZ_DIREKT_OP_CI} (AUC: {AS_AUC_DIREKT_OP_CI}). Bei Patienten nach nRCT (nRCT-Gruppe, ${KOLLEKTIV_TEXT_NRCT}) betrug die Sensitivität {AS_SENS_NRCT_CI} und die Spezifität {AS_SPEZ_NRCT_CI} (AUC: {AS_AUC_NRCT_CI}).</p>
            `,
            ergebnisse_literatur_t2_performance: `
                <p>Die diagnostische Güte der evaluierten Literatur-basierten T2-Kriteriensets ist in <a href="{TABLE_LITERATURE_T2_PERFORMANCE_REF_LINK}">Tabelle 4</a> zusammengefasst. Für das Kriterienset nach Koh et al. (2008) [{STUDY_REF_KOH_2008}], angewendet auf das ${KOLLEKTIV_TEXT_KOH_APPLICABLE}, ergab sich eine Sensitivität von {KOH_SENS_CI} und eine Spezifität von {KOH_SPEZ_CI} (AUC {KOH_AUC_CI}). Die Kriterien nach Barbaro et al. (2024) [{STUDY_REF_BARBARO_2024}], angewendet auf das ${KOLLEKTIV_TEXT_BARBARO_APPLICABLE}, zeigten eine Sensitivität von {BARBARO_SENS_CI} und eine Spezifität von {BARBARO_SPEZ_CI} (AUC {BARBARO_AUC_CI}). Die ESGAR Konsensus Kriterien (Beets-Tan et al., 2018 [{STUDY_REF_ESGAR_2018}], evaluiert durch Rutegård et al., 2025 [{STUDY_REF_RUTEGARD_2025}]), angewendet auf das ${KOLLEKTIV_TEXT_ESGAR_APPLICABLE}, erreichten eine Sensitivität von {ESGAR_SENS_CI} und eine Spezifität von {ESGAR_SPEZ_CI} (AUC {ESGAR_AUC_CI}).</p>
            `,
            ergebnisse_optimierte_t2_performance: `
                <p>Mittels eines Brute-Force-Algorithmus wurden für jedes der drei Kollektive spezifische T2-Kriteriensets identifiziert, welche die ${BF_TARGET_METRIC_NAME} maximieren. Die Definition dieser optimierten Kriteriensets ist im Methodenteil (Abschnitt 2.5) und implizit in <a href="{TABLE_LITERATURE_T2_CRITERIA_REF_LINK}">Tabelle 2</a> aufgeführt. Die diagnostische Güte dieser optimierten Sets ist in <a href="{TABLE_OPTIMIZED_T2_PERFORMANCE_REF_LINK}">Tabelle 5</a> dargestellt.</p>
                <ul>
                    <li>Für das Gesamtkollektiv (${KOLLEKTIV_TEXT_GESAMT}) erreichten die optimierten Kriterien eine Sensitivität von {BF_SENS_GESAMT_CI}, eine Spezifität von {BF_SPEZ_GESAMT_CI} und eine AUC von {BF_AUC_GESAMT_CI}.</li>
                    <li>Für das Direkt-OP-Kollektiv (${KOLLEKTIV_TEXT_DIREKT_OP}) erreichten die optimierten Kriterien eine Sensitivität von {BF_SENS_DIREKT_OP_CI}, eine Spezifität von {BF_SPEZ_DIREKT_OP_CI} und eine AUC von {BF_AUC_DIREKT_OP_CI}.</li>
                    <li>Für das nRCT-Kollektiv (${KOLLEKTIV_TEXT_NRCT}) erreichten die optimierten Kriterien eine Sensitivität von {BF_SENS_NRCT_CI}, eine Spezifität von {BF_SPEZ_NRCT_CI} und eine AUC von {BF_AUC_NRCT_CI}.</li>
                </ul>
            `,
            ergebnisse_vergleich_performance: `
                <p>Der direkte statistische Vergleich der diagnostischen Güte zwischen dem Avocado Sign (AS) und den ausgewählten T2-Kriteriensets (Literatur-basiert und Brute-Force-optimiert für ${BF_TARGET_METRIC_NAME}) ist in <a href="{TABLE_COMPARISON_AS_VS_T2_REF_LINK}">Tabelle 6</a> zusammengefasst. <a href="{FIG_COMPARISON_PERFORMANCE_GESAMT_REF_LINK}">Abbildung 2a</a>, <a href="{FIG_COMPARISON_PERFORMANCE_DIREKT_OP_REF_LINK}">2b</a> und <a href="{FIG_COMPARISON_PERFORMANCE_NRCT_REF_LINK}">2c</a> visualisieren die Schlüsselmetriken vergleichend für die drei Kollektive.</p>
                <h4>Vergleich im Gesamtkollektiv</h4>
                <p>Im Vergleich des AS (AUC {AS_AUC_GESAMT}) mit den Kriterien nach Koh et al. (AUC {KOH_AUC_GESAMT}) zeigte sich für die Accuracy ein p-Wert von {P_VALUE_MCNEMAR_AS_VS_KOH_GESAMT} (McNemar) und für die AUC ein p-Wert von {P_VALUE_DELONG_AS_VS_KOH_GESAMT} (DeLong). Der Unterschied in der AUC betrug {DIFF_AUC_AS_VS_KOH_GESAMT}.</p>
                <p>Gegenüber den für die {BF_TARGET_METRIC_NAME} optimierten T2-Kriterien (AUC {BF_AUC_GESAMT}) ergab sich für die Accuracy ein p-Wert von {P_VALUE_MCNEMAR_AS_VS_BF_GESAMT} (McNemar) und für die AUC ein p-Wert von {P_VALUE_DELONG_AS_VS_BF_GESAMT} (DeLong). Der Unterschied in der AUC betrug {DIFF_AUC_AS_VS_BF_GESAMT}.</p>
                <h4>Vergleich im Direkt-OP-Kollektiv</h4>
                <p>Im Vergleich des AS (AUC {AS_AUC_DIREKT_OP}) mit den ESGAR-Kriterien (eval. Rutegård et al.) (AUC {ESGAR_AUC_DIREKT_OP}) zeigte sich für die Accuracy ein p-Wert von {P_VALUE_MCNEMAR_AS_VS_ESGAR_DIREKT_OP} (McNemar) und für die AUC ein p-Wert von {P_VALUE_DELONG_AS_VS_ESGAR_DIREKT_OP} (DeLong). Der Unterschied in der AUC betrug {DIFF_AUC_AS_VS_ESGAR_DIREKT_OP}.</p>
                <p>Gegenüber den für die {BF_TARGET_METRIC_NAME} optimierten T2-Kriterien (AUC {BF_AUC_DIREKT_OP}) ergab sich für die Accuracy ein p-Wert von {P_VALUE_MCNEMAR_AS_VS_BF_DIREKT_OP} (McNemar) und für die AUC ein p-Wert von {P_VALUE_DELONG_AS_VS_BF_DIREKT_OP} (DeLong). Der Unterschied in der AUC betrug {DIFF_AUC_AS_VS_BF_DIREKT_OP}.</p>
                <h4>Vergleich im nRCT-Kollektiv</h4>
                <p>Im Vergleich des AS (AUC {AS_AUC_NRCT}) mit den Kriterien nach Barbaro et al. (AUC {BARBARO_AUC_NRCT}) zeigte sich für die Accuracy ein p-Wert von {P_VALUE_MCNEMAR_AS_VS_BARBARO_NRCT} (McNemar) und für die AUC ein p-Wert von {P_VALUE_DELONG_AS_VS_BARBARO_NRCT} (DeLong). Der Unterschied in der AUC betrug {DIFF_AUC_AS_VS_BARBARO_NRCT}.</p>
                <p>Gegenüber den für die {BF_TARGET_METRIC_NAME} optimierten T2-Kriterien (AUC {BF_AUC_NRCT}) ergab sich für die Accuracy ein p-Wert von {P_VALUE_MCNEMAR_AS_VS_BF_NRCT} (McNemar) und für die AUC ein p-Wert von {P_VALUE_DELONG_AS_VS_BF_NRCT} (DeLong). Der Unterschied in der AUC betrug {DIFF_AUC_AS_VS_BF_NRCT}.</p>
            `
        },
        diskussion: {
            // Platzhalter für Diskussionstexte
            diskussion_hauptergebnisse: `<p>[Zusammenfassung der Hauptergebnisse und deren Bedeutung im Kontext der bestehenden Literatur und klinischen Praxis...]</p>`,
            diskussion_as_vs_t2: `<p>[Detaillierte Diskussion des Vergleichs zwischen Avocado Sign und T2-Kriterien, Stärken und Schwächen beider Ansätze...]</p>`,
            diskussion_limitatioenen: `<p>[Diskussion der Limitationen dieser Studie, z.B. retrospektiver Charakter, monozentrisch, Fallzahl...]</p>`,
            diskussion_ausblick: `<p>[Ausblick auf zukünftige Forschungsrichtungen und mögliche klinische Implikationen...]</p>`,
            diskussion_schlussfolgerung: `<p>[Prägnante Schlussfolgerung der Studie...]</p>`
        },
        einleitung: {
            einleitung_hintergrund: `<p>[Hintergrundinformationen zum Rektumkarzinom-Staging, Herausforderungen bei der Lymphknotenbeurteilung und Bedeutung einer akkuraten Diagnostik. Einführung des Avocado Signs als vielversprechender neuer Marker basierend auf {STUDY_REF_AVOCADO_SIGN}. Nennung etablierter T2-Kriterien und der Notwendigkeit eines direkten Vergleichs.]</p>`,
            einleitung_zielsetzung: `<p>[Klare Formulierung der Zielsetzung dieser Studie: Vergleich der diagnostischen Performance des Avocado Signs mit etablierten und optimierten T2-Kriterien zur Prädiktion des Lymphknotenstatus beim Rektumkarzinom.]</p>`
        },
        abstract: {
            abstract_text: `
                <p><strong>Objectives:</strong> To compare the diagnostic performance of the Avocado Sign (AS) with established and optimized T2-weighted MRI criteria for predicting mesorectal lymph node (LN) involvement in rectal cancer.</p>
                <p><strong>Methods:</strong> This retrospective single-center study included {N_GESAMT} patients ({N_DIREKT_OP} primary surgery, {N_NRCT} neoadjuvant chemoradiotherapy [nCRT]) with rectal cancer who underwent 3.0T MRI including contrast-enhanced T1-weighted sequences. The AS was assessed on restaging (nCRT group) or baseline (surgery-alone group) MRI. T2-weighted criteria (size, shape, border, homogeneity, signal) were evaluated based on literature (Koh et al. [{STUDY_REF_KOH_2008}], Barbaro et al. [{STUDY_REF_BARBARO_2024}], ESGAR 2016/Rutegård et al. [{STUDY_REF_RUTEGARD_2025}, {STUDY_REF_ESGAR_2018}]) and optimized using a brute-force algorithm targeting {BF_TARGET_METRIC_NAME}. Histopathology served as reference. Sensitivity, specificity, PPV, NPV, accuracy, and AUC with 95% CIs were calculated. McNemar and DeLong tests were used for comparisons (p < {ALPHA_LEVEL_TEXT}).</p>
                <p><strong>Results:</strong> The AS demonstrated high overall accuracy (AUC {AS_AUC_GESAMT_CI}). Performance of literature-based T2 criteria varied (e.g., ESGAR/Rutegård for primary surgery: AUC {ESGAR_AUC_DIREKT_OP_CI}). Brute-force optimized T2 criteria achieved an AUC of {BF_AUC_GESAMT_CI} (overall cohort), {BF_AUC_DIREKT_OP_CI} (primary surgery), and {BF_AUC_NRCT_CI} (nCRT cohort) for {BF_TARGET_METRIC_NAME}. In direct comparison, [Summarize key comparison results, e.g., 'AS showed significantly higher/comparable AUC than specific T2 sets in certain cohorts... p-values'].</p>
                <p><strong>Conclusion:</strong> [Summarize main conclusion regarding AS performance vs. T2 criteria and its potential clinical impact.]</p>
                <p><strong>Key Points:</strong><br>
                - [Key finding 1, e.g., Avocado Sign provides high diagnostic accuracy for N-staging in rectal cancer.]<br>
                - [Key finding 2, e.g., Performance of Avocado Sign was robust across primary surgery and post-nCRT cohorts.]<br>
                - [Key finding 3, e.g., Avocado Sign demonstrated [superior/comparable/inferior] performance to [specific T2 criteria set] for [specific metric/cohort].]</p>
            `
        },
        referenzen: {
            // Wird später dynamisch generiert
            referenzen_liste: `<p>[Liste der zitierten Referenzen im Stil von Radiology.]</p>`
        }
    },
    en: {
        methoden: {
            methoden_studienanlage: `
                <p>This study was conducted as a retrospective analysis of a prospectively maintained, single-center patient cohort with histologically confirmed rectal cancer. The primary study population and the underlying imaging datasets for the initial assessment of the Avocado Sign (AS) are identical to those of the original publication on the Avocado Sign by Lurz & Schäfer (2025) [{STUDY_REF_AVOCADO_SIGN}]. The aim of this extended investigation is a detailed comparison of the diagnostic performance of the AS with established and optimized T2-weighted morphological criteria for the prediction of mesorectal lymph node status (N-status), as well as the provision of an exploratory tool for further analyses.</p>
                <p>All analyses and criteria evaluations presented herein were performed using an interactive web application ({APP_NAME} v{APP_VERSION}), specifically developed for this and subsequent studies. This tool allows for the flexible definition and application of T2 criteria sets, automated optimization of criteria combinations, and comprehensive statistical evaluation and visualization of results. The study was conducted in accordance with the principles of the Declaration of Helsinki. The study protocol was approved by the local ethics committee (Ethics Committee of the Saxony State Medical Association, Vote No. {ETHICS_VOTE_NUMBER}). Given the retrospective nature of the analysis on pseudonymized data, the ethics committee waived the need for re-obtaining written informed consent from patients for this specific extended evaluation, as general consent for scientific evaluation was provided as part of the primary study.</p>
            `,
            methoden_patientenkollektiv: `
                <p>The study cohort comprised {N_GESAMT} consecutive patients with histologically confirmed rectal cancer who were treated at Klinikum St. Georg, Leipzig, between {STUDY_PERIOD} and included in the initial Avocado Sign study [{STUDY_REF_AVOCADO_SIGN}]. Of these, {N_NRCT} patients received neoadjuvant chemoradiotherapy (nCRT group), while {N_DIREKT_OP} patients underwent primary surgery (direct surgery group). The median age in the overall cohort was {MEDIAN_AGE_GESAMT} years (range: {MIN_AGE_GESAMT}–{MAX_AGE_GESAMT} years), and {PERCENT_MALE_GESAMT}% ({N_MALE_GESAMT}/{N_GESAMT}) of the patients were male. Detailed patient characteristics, stratified by treatment group, are presented in <a href="{TABLE_PATIENT_CHARACTERISTICS_REF_LINK}">Table 1</a>.</p>
                <p>Inclusion criteria for the primary study were an age of at least 18 years and histologically confirmed rectal cancer. Exclusion criteria included unresectable tumors and contraindications to MRI examination. For the present extended analysis, all patients from the primary study for whom complete datasets regarding T1-weighted contrast-enhanced and T2-weighted lymph node characteristics were available were included.</p>
            `,
            methoden_mrt_protokoll: `
                <p>All MRI examinations were performed on a {MRT_SYSTEM} using body and spine array coils. The standardized imaging protocol included high-resolution T2-weighted turbo spin-echo (TSE) sequences in sagittal, axial, and coronal planes (slice thickness {T2_SLICE_THICKNESS}), as well as an axial diffusion-weighted imaging (DWI) sequence. For the assessment of the Avocado Sign, as described in the primary study [{STUDY_REF_AVOCADO_SIGN}], a contrast-enhanced axial T1-weighted volumetric interpolated breath-hold examination (VIBE) with Dixon fat suppression was acquired.</p>
                <p>A macrocyclic gadolinium-based contrast agent ({CONTRAST_AGENT_AS}) was administered intravenously at a weight-based dose (0.2 mL/kg body weight). Contrast-enhanced images were acquired immediately after the full administration of the contrast agent. Butylscopolamine was administered to reduce motion artifacts. The imaging protocol was identical for baseline staging and restaging examinations (in patients from the nCRT group).</p>
            `,
            methoden_as_definition: `
                <p>The Avocado Sign, as defined in the original study [{STUDY_REF_AVOCADO_SIGN}], was evaluated on contrast-enhanced T1-weighted images. It is characterized as a clearly demarcated, hypointense core within an otherwise homogeneously hyperintense lymph node, irrespective of node size or shape (see Figure 2 in [{STUDY_REF_AVOCADO_SIGN}]). Assessment was performed for all mesorectal lymph nodes visible on T1-weighted contrast-enhanced MRI. A patient was classified as Avocado Sign-positive (AS+) if at least one lymph node exhibited this sign. Image analysis was performed by two radiologists (experience: {RADIOLOGIST_EXPERIENCE_1} and {RADIOLOGIST_EXPERIENCE_2} years in abdominal MRI, respectively), who also conducted the primary study, independently and blinded to histopathological results and T2-weighted features. Discrepancies were resolved by consensus with a third, similarly experienced radiologist (experience: {RADIOLOGIST_EXPERIENCE_3} years). For patients in the nCRT group, AS assessment was performed on restaging MRI images.</p>
            `,
            methoden_t2_definition: `
                <p>The morphological T2-weighted criteria (size [short-axis diameter in mm], shape ['round', 'oval'], border ['smooth', 'irregular'], homogeneity ['homogeneous', 'heterogeneous'], and signal intensity ['low', 'intermediate', 'high']) were assessed for every mesorectal lymph node visible on high-resolution T2w-MRI by the same two radiologists who evaluated the Avocado Sign. The assessment was performed by consensus and blinded to the pathological N-status and the Avocado Sign status.</p>
                <p>For the comparison of diagnostic performance, the following T2 criteria sets were utilized:</p>
                <ol>
                    <li><strong>Literature-based T2 criteria sets:</strong> A selection of established criteria from the literature was implemented and applied to the respective subgroups or the entire cohort of our dataset (details see <a href="{TABLE_LITERATURE_T2_CRITERIA_REF_LINK}">Table 2</a>):
                        <ul>
                            <li>Koh et al. (2008) [{STUDY_REF_KOH_2008}]: Defined as "${KOH_2008_DEFINITION_EN}". This set was applied to the '${KOH_2008_APPLICABLE_KOLLEKTIV_EN}' cohort in our analysis.</li>
                            <li>Barbaro et al. (2024) [{STUDY_REF_BARBARO_2024}]: Defined as "${BARBARO_2024_DEFINITION_EN}". This set was specifically evaluated for the '${BARBARO_2024_APPLICABLE_KOLLEKTIV_EN}' cohort (restaging).</li>
                            <li>ESGAR Consensus Criteria (Beets-Tan et al., 2018 [{STUDY_REF_ESGAR_2018}]), as evaluated by Rutegård et al. (2025) [{STUDY_REF_RUTEGARD_2025}]: Defined as "${ESGAR_2016_RUTEGARD_2025_DEFINITION_EN}". This set was primarily applied to the '${ESGAR_2016_RUTEGARD_2025_APPLICABLE_KOLLEKTIV_EN}' cohort (primary staging).</li>
                        </ul>
                    </li>
                    <li><strong>Brute-force optimized T2 criteria:</strong> Using a brute-force algorithm implemented in the analysis tool, combinations of the five T2 features and AND/OR logic that maximize the primary endpoint of this study – <strong>{BF_TARGET_METRIC_NAME}</strong> – were identified for each of the three main cohorts (Overall, Direct Surgery, nCRT). The resulting cohort-specific optimized criteria sets were:
                        <ul>
                            <li><strong>Overall cohort:</strong> {BF_OPTIMIZED_GESAMT_DEFINITION_EN} (target metric: {BF_TARGET_METRIC_NAME}, value: {BF_OPTIMIZED_GESAMT_VALUE})</li>
                            <li><strong>Direct surgery cohort:</strong> {BF_OPTIMIZED_DIREKT_OP_DEFINITION_EN} (target metric: {BF_TARGET_METRIC_NAME}, value: {BF_OPTIMIZED_DIREKT_OP_VALUE})</li>
                            <li><strong>nCRT cohort:</strong> {BF_OPTIMIZED_NRCT_DEFINITION_EN} (target metric: {BF_TARGET_METRIC_NAME}, value: {BF_OPTIMIZED_NRCT_VALUE})</li>
                        </ul>
                    </li>
                     <li><strong>Currently set T2 criteria in the analysis tool:</strong> The criteria currently set in the tool at the time of final analysis were: {APPLIED_T2_CRITERIA_STRING_EN}. These primarily served as a reference point for exploratory analyses and to demonstrate the tool's flexibility.</li>
                </ol>
                <p>A lymph node was considered T2-positive for a given criteria set if it met the specific conditions of that set. A patient was considered T2-positive if at least one lymph node was rated positive according to the respective criteria set.</p>
            `,
            methoden_referenzstandard: `
                <p>Histopathological examination of surgical specimens after total mesorectal excision (TME) served as the reference standard for lymph node status. All mesorectal lymph nodes were processed and microscopically evaluated by experienced pathologists according to established standard protocols. A patient's N-status was defined as positive (N+) if at least one lymph node was histologically identified as metastatic. Otherwise, the patient was considered N-negative (N0).</p>
            `,
            methoden_statistische_analyse: `
                <p>Descriptive statistics included the calculation of medians, means, standard deviations (SD), minima, and maxima for continuous variables, as well as absolute frequencies and percentages for categorical data. The diagnostic performance of the Avocado Sign and the various T2 criteria sets (literature-based and brute-force optimized) was evaluated using sensitivity, specificity, positive predictive value (PPV), negative predictive value (NPV), accuracy (ACC), balanced accuracy (BalAcc), and the area under the Receiver Operating Characteristic curve (AUC)—equivalent to BalAcc for binary tests. Two-sided 95% confidence intervals (CI) were calculated for these metrics. The ${CI_METHOD_PROPORTION} method was used for proportions (sensitivity, specificity, PPV, NPV, accuracy). For BalAcc (AUC) and F1-score, the ${CI_METHOD_EFFECTSIZE} method with ${BOOTSTRAP_REPLICATIONS} replications was applied.</p>
                <p>Statistical comparison of diagnostic performance (accuracy, AUC) between the Avocado Sign and the respective T2 criteria sets within the same patient group (paired data) was performed using McNemar's test for paired nominal data and DeLong's test for AUC comparison. Comparison of performance metrics between independent cohorts (e.g., direct surgery vs. nCRT group) was conducted using Fisher's exact test for rates (such as accuracy) and a Z-test for AUC comparison based on their bootstrap standard errors. Odds Ratios (OR) and Risk Differences (RD) were calculated to quantify associations, also with 95% CIs. The Phi coefficient (φ) was used as a measure of the strength of association between binary features. For comparing distributions of continuous variables between two independent groups, the Mann-Whitney U test was used. A p-value < ${ALPHA_LEVEL_TEXT} was considered statistically significant. All statistical analyses were conducted using the aforementioned custom-developed web application ({APP_NAME} v{APP_VERSION}), which is based on standard libraries for statistical computations and JavaScript.</p>
            `
        },
        ergebnisse: {
            ergebnisse_patientencharakteristika: `
                <p>The characteristics of the {N_GESAMT} patients included in the study are summarized in <a href="{TABLE_PATIENT_CHARACTERISTICS_REF_LINK}">Table 1</a> and correspond to the data from the initial Avocado Sign study [{STUDY_REF_AVOCADO_SIGN}]. The overall cohort consisted of {N_DIREKT_OP} patients who underwent upfront surgery (direct surgery group) and {N_NRCT} patients who received neoadjuvant chemoradiotherapy (nCRT group). The median age in the overall cohort was {MEDIAN_AGE_GESAMT_EN} years (range {MIN_AGE_GESAMT_EN}–{MAX_AGE_GESAMT_EN}), and {PERCENT_MALE_GESAMT}% were male. A histopathologically confirmed positive lymph node status (N+) was found in {N_PLUS_GESAMT} of {N_GESAMT} patients ({PERCENT_N_PLUS_GESAMT}%) in the overall cohort. The age and gender distribution in the overall cohort is shown in <a href="{FIG_AGE_DISTRIBUTION_REF_LINK}">Figure 1a</a> and <a href="{FIG_GENDER_DISTRIBUTION_REF_LINK}">Figure 1b</a>.</p>
            `,
            ergebnisse_as_performance: `
                <p>The diagnostic performance of the Avocado Sign (AS) for predicting pathological N-status is detailed in <a href="{TABLE_AS_PERFORMANCE_REF_LINK}">Table 3</a> for the overall cohort and subgroups. In the overall cohort (${KOLLEKTIV_TEXT_GESAMT_EN}), the AS achieved a sensitivity of {AS_SENS_GESAMT_CI_EN}, a specificity of {AS_SPEZ_GESAMT_CI_EN}, a positive predictive value (PPV) of {AS_PPV_GESAMT_CI_EN}, a negative predictive value (NPV) of {AS_NPV_GESAMT_CI_EN}, and an accuracy of {AS_ACC_GESAMT_CI_EN}. The AUC (Balanced Accuracy) was {AS_AUC_GESAMT_CI_EN}.</p>
                <p>In the subgroup of patients undergoing upfront surgery (direct surgery group, ${KOLLEKTIV_TEXT_DIREKT_OP_EN}), the AS showed a sensitivity of {AS_SENS_DIREKT_OP_CI_EN} and a specificity of {AS_SPEZ_DIREKT_OP_CI_EN} (AUC: {AS_AUC_DIREKT_OP_CI_EN}). For patients after nCRT (nCRT group, ${KOLLEKTIV_TEXT_NRCT_EN}), the sensitivity was {AS_SENS_NRCT_CI_EN} and the specificity was {AS_SPEZ_NRCT_CI_EN} (AUC: {AS_AUC_NRCT_CI_EN}).</p>
            `,
            ergebnisse_literatur_t2_performance: `
                <p>The diagnostic performance of the evaluated literature-based T2 criteria sets is summarized in <a href="{TABLE_LITERATURE_T2_PERFORMANCE_REF_LINK}">Table 4</a>. For the criteria set according to Koh et al. (2008) [{STUDY_REF_KOH_2008}], applied to the ${KOLLEKTIV_TEXT_KOH_APPLICABLE_EN}, a sensitivity of {KOH_SENS_CI_EN} and a specificity of {KOH_SPEZ_CI_EN} (AUC {KOH_AUC_CI_EN}) were observed. The criteria by Barbaro et al. (2024) [{STUDY_REF_BARBARO_2024}], applied to the ${KOLLEKTIV_TEXT_BARBARO_APPLICABLE_EN}, showed a sensitivity of {BARBARO_SENS_CI_EN} and a specificity of {BARBARO_SPEZ_CI_EN} (AUC {BARBARO_AUC_CI_EN}). The ESGAR Consensus Criteria (Beets-Tan et al., 2018 [{STUDY_REF_ESGAR_2018}], evaluated by Rutegård et al., 2025 [{STUDY_REF_RUTEGARD_2025}]), applied to the ${KOLLEKTIV_TEXT_ESGAR_APPLICABLE_EN}, achieved a sensitivity of {ESGAR_SENS_CI_EN} and a specificity of {ESGAR_SPEZ_CI_EN} (AUC {ESGAR_AUC_CI_EN}).</p>
            `,
            ergebnisse_optimierte_t2_performance: `
                <p>Using a brute-force algorithm, specific T2 criteria sets maximizing ${BF_TARGET_METRIC_NAME} were identified for each of the three cohorts. The definition of these optimized criteria sets is detailed in the Methods section (Section 2.5) and implicitly in <a href="{TABLE_LITERATURE_T2_CRITERIA_REF_LINK}">Table 2</a>. The diagnostic performance of these optimized sets is presented in <a href="{TABLE_OPTIMIZED_T2_PERFORMANCE_REF_LINK}">Table 5</a>.</p>
                <ul>
                    <li>For the overall cohort (${KOLLEKTIV_TEXT_GESAMT_EN}), the optimized criteria achieved a sensitivity of {BF_SENS_GESAMT_CI_EN}, a specificity of {BF_SPEZ_GESAMT_CI_EN}, and an AUC of {BF_AUC_GESAMT_CI_EN}.</li>
                    <li>For the direct surgery cohort (${KOLLEKTIV_TEXT_DIREKT_OP_EN}), the optimized criteria achieved a sensitivity of {BF_SENS_DIREKT_OP_CI_EN}, a specificity of {BF_SPEZ_DIREKT_OP_CI_EN}, and an AUC of {BF_AUC_DIREKT_OP_CI_EN}.</li>
                    <li>For the nCRT cohort (${KOLLEKTIV_TEXT_NRCT_EN}), the optimized criteria achieved a sensitivity of {BF_SENS_NRCT_CI_EN}, a specificity of {BF_SPEZ_NRCT_CI_EN}, and an AUC of {BF_AUC_NRCT_CI_EN}.</li>
                </ul>
            `,
            ergebnisse_vergleich_performance: `
                <p>The direct statistical comparison of diagnostic performance between the Avocado Sign (AS) and the selected T2 criteria sets (literature-based and brute-force optimized for ${BF_TARGET_METRIC_NAME}) is summarized in <a href="{TABLE_COMPARISON_AS_VS_T2_REF_LINK}">Table 6</a>. <a href="{FIG_COMPARISON_PERFORMANCE_GESAMT_REF_LINK}">Figure 2a</a>, <a href="{FIG_COMPARISON_PERFORMANCE_DIREKT_OP_REF_LINK}">2b</a>, and <a href="{FIG_COMPARISON_PERFORMANCE_NRCT_REF_LINK}">2c</a> provide a comparative visualization of key metrics across the three cohorts.</p>
                <h4>Comparison in the Overall Cohort</h4>
                <p>Comparing AS (AUC {AS_AUC_GESAMT_EN}) with the criteria by Koh et al. (AUC {KOH_AUC_GESAMT_EN}), the p-value for accuracy was {P_VALUE_MCNEMAR_AS_VS_KOH_GESAMT_EN} (McNemar) and for AUC was {P_VALUE_DELONG_AS_VS_KOH_GESAMT_EN} (DeLong). The difference in AUC was {DIFF_AUC_AS_VS_KOH_GESAMT_EN}.</p>
                <p>Compared to the T2 criteria optimized for {BF_TARGET_METRIC_NAME} (AUC {BF_AUC_GESAMT_EN}), the p-value for accuracy was {P_VALUE_MCNEMAR_AS_VS_BF_GESAMT_EN} (McNemar) and for AUC was {P_VALUE_DELONG_AS_VS_BF_GESAMT_EN} (DeLong). The difference in AUC was {DIFF_AUC_AS_VS_BF_GESAMT_EN}.</p>
                <h4>Comparison in the Direct Surgery Cohort</h4>
                <p>Comparing AS (AUC {AS_AUC_DIREKT_OP_EN}) with the ESGAR criteria (eval. Rutegård et al.) (AUC {ESGAR_AUC_DIREKT_OP_EN}), the p-value for accuracy was {P_VALUE_MCNEMAR_AS_VS_ESGAR_DIREKT_OP_EN} (McNemar) and for AUC was {P_VALUE_DELONG_AS_VS_ESGAR_DIREKT_OP_EN} (DeLong). The difference in AUC was {DIFF_AUC_AS_VS_ESGAR_DIREKT_OP_EN}.</p>
                <p>Compared to the T2 criteria optimized for {BF_TARGET_METRIC_NAME} (AUC {BF_AUC_DIREKT_OP_EN}), the p-value for accuracy was {P_VALUE_MCNEMAR_AS_VS_BF_DIREKT_OP_EN} (McNemar) and for AUC was {P_VALUE_DELONG_AS_VS_BF_DIREKT_OP_EN} (DeLong). The difference in AUC was {DIFF_AUC_AS_VS_BF_DIREKT_OP_EN}.</p>
                <h4>Comparison in the nCRT Cohort</h4>
                <p>Comparing AS (AUC {AS_AUC_NRCT_EN}) with the criteria by Barbaro et al. (AUC {BARBARO_AUC_NRCT_EN}), the p-value for accuracy was {P_VALUE_MCNEMAR_AS_VS_BARBARO_NRCT_EN} (McNemar) and for AUC was {P_VALUE_DELONG_AS_VS_BARBARO_NRCT_EN} (DeLong). The difference in AUC was {DIFF_AUC_AS_VS_BARBARO_NRCT_EN}.</p>
                <p>Compared to the T2 criteria optimized for {BF_TARGET_METRIC_NAME} (AUC {BF_AUC_NRCT_EN}), the p-value for accuracy was {P_VALUE_MCNEMAR_AS_VS_BF_NRCT_EN} (McNemar) and for AUC was {P_VALUE_DELONG_AS_VS_BF_NRCT_EN} (DeLong). The difference in AUC was {DIFF_AUC_AS_VS_BF_NRCT_EN}.</p>
            `
        },
        diskussion: {
            diskussion_hauptergebnisse: `<p>[Summary of main findings and their significance in the context of existing literature and clinical practice...]</p>`,
            diskussion_as_vs_t2: `<p>[Detailed discussion of the comparison between Avocado Sign and T2 criteria, strengths and weaknesses of both approaches...]</p>`,
            diskussion_limitatioenen: `<p>[Discussion of the limitations of this study, e.g., retrospective nature, single-center, sample size...]</p>`,
            diskussion_ausblick: `<p>[Outlook on future research directions and potential clinical implications...]</p>`,
            diskussion_schlussfolgerung: `<p>[Concise conclusion of the study...]</p>`
        },
        einleitung: {
            einleitung_hintergrund: `<p>[Background information on rectal cancer staging, challenges in lymph node assessment, and the importance of accurate diagnostics. Introduction of the Avocado Sign as a promising new marker based on {STUDY_REF_AVOCADO_SIGN}. Mention of established T2 criteria and the need for direct comparison.]</p>`,
            einleitung_zielsetzung: `<p>[Clear formulation of the objective of this study: To compare the diagnostic performance of the Avocado Sign with established and optimized T2-weighted criteria for predicting lymph node status in rectal cancer.]</p>`
        },
        abstract: {
            abstract_text: `
                <p><strong>Objectives:</strong> To compare the diagnostic performance of the Avocado Sign (AS) with established and optimized T2-weighted MRI criteria for predicting mesorectal lymph node (LN) involvement in rectal cancer.</p>
                <p><strong>Methods:</strong> This retrospective single-center study included {N_GESAMT_EN} patients ({N_DIREKT_OP_EN} primary surgery, {N_NRCT_EN} neoadjuvant chemoradiotherapy [nCRT]) with rectal cancer who underwent 3.0T MRI including contrast-enhanced T1-weighted sequences. The AS was assessed on restaging (nCRT group) or baseline (surgery-alone group) MRI. T2-weighted criteria (size, shape, border, homogeneity, signal) were evaluated based on literature (Koh et al. [{STUDY_REF_KOH_2008_EN}], Barbaro et al. [{STUDY_REF_BARBARO_2024_EN}], ESGAR 2016/Rutegård et al. [{STUDY_REF_RUTEGARD_2025_EN}, {STUDY_REF_ESGAR_2018_EN}]) and optimized using a brute-force algorithm targeting {BF_TARGET_METRIC_NAME}. Histopathology served as reference. Sensitivity, specificity, PPV, NPV, accuracy, and AUC with 95% CIs were calculated. McNemar and DeLong tests were used for comparisons (p < {ALPHA_LEVEL_TEXT}).</p>
                <p><strong>Results:</strong> The AS demonstrated high overall accuracy (AUC {AS_AUC_GESAMT_CI_EN}). Performance of literature-based T2 criteria varied (e.g., ESGAR/Rutegård for primary surgery: AUC {ESGAR_AUC_DIREKT_OP_CI_EN}). Brute-force optimized T2 criteria achieved an AUC of {BF_AUC_GESAMT_CI_EN} (overall cohort), {BF_AUC_DIREKT_OP_CI_EN} (primary surgery), and {BF_AUC_NRCT_CI_EN} (nCRT cohort) for {BF_TARGET_METRIC_NAME}. In direct comparison, [Summarize key comparison results, e.g., 'AS showed significantly higher/comparable AUC than specific T2 sets in certain cohorts... p-values'].</p>
                <p><strong>Conclusion:</strong> [Summarize main conclusion regarding AS performance vs. T2 criteria and its potential clinical impact.]</p>
                <p><strong>Key Points:</strong><br>
                - [Key finding 1, e.g., Avocado Sign provides high diagnostic accuracy for N-staging in rectal cancer.]<br>
                - [Key finding 2, e.g., Performance of Avocado Sign was robust across primary surgery and post-nCRT cohorts.]<br>
                - [Key finding 3, e.g., Avocado Sign demonstrated [superior/comparable/inferior] performance to [specific T2 criteria set] for [specific metric/cohort].]</p>
            `
        },
        referenzen: {
            referenzen_liste: `<p>[List of cited references in Radiology style.]</p>`
        }
    }
};

if (typeof Object.freeze === 'function') {
    Object.freeze(PUBLICATION_TEXT_TEMPLATES);
}
